version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    env_file:
      - ./.env
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD #Root password for MySql server

    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    restart: unless-stopped

  app:
    build: ./
    depends_on:
      - mysql
    ports:
      - "8089:8089"
    restart: unless-stopped
    container_name: tp_foyer
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysql:3306/db?createDatabaseIfNotExist=true",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update",
        "management.endpoints.web.exposure.include":"prometheus",
        "management.prometheus.metrics.export.enabled":"true"
      }'
volumes:
  db:
    driver: local


